name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate PNGs
        run: npm run generate-pngs

      - name: Generate hi-res PNGs
        run: npm run generate-pngs -- --size 2048 --outdir ./png-2048

      - name: Create tar archive
        run: tar -czvf blobbee.tar.gz -C png .

      - name: Generate meta
        run: npm run generate-meta

      - name: Generate preview
        run: npm run generate-preview

      - name: Create PNG archive
        run: zip -r blobbee.zip png

      - name: Create hi-res PNG archive
        run: zip -r blobbee-hires.zip png-2048

      - name: Generate checksum
        id: checksum
        run:
          echo "checksum=$(sha256sum blobbee.zip | cut -d " " -f 1)" >>
          $GITHUB_OUTPUT

      - name: Generate manifest
        run: npm run generate-manifest ${{ steps.checksum.outputs.checksum }}

      - name: Create SVG archive
        run: zip -r blobbee-svg.zip svg

      - name: Create changelog
        id: changelog
        if: ${{ !contains(github.ref_name, 'prerelease') }}
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: 'changelog-config.json'
          commitMode: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: ${{ !contains(github.ref_name, 'prerelease') }}
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ contains(github.ref_name, 'prerelease') }}
          files: |
            preview.png
            blobbee.zip
            blobbee-hires.zip
            blobbee.tar.gz
            blobbee-svg.zip
            manifest.json
            filemap.json

      - name: Create prerelease
        uses: softprops/action-gh-release@v2
        if: ${{ contains(github.ref_name, 'prerelease') }}
        with:
          body:
            '![A grid of bee emojis making various
            expressions](https://github.com/olivvybee/blobbee/releases/download/${{github.ref_name}}/preview.png)'
          prerelease: true
          files: |
            preview.png
            blobbee.zip
            blobbee-hires.zip
            blobbee.tar.gz
            blobbee-svg.zip
            manifest.json
            filemap.json
